################################################################################
# Copyright (c) 2017-2021 Argon Design Ltd. All rights reserved.
# This file is covered by the BSD (with attribution) license.
# See the LICENSE file for the precise wording of the license.
################################################################################

# To validate execute:
# curl --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  require_ci_to_pass: yes

ignore:
  - "verilator"
  - "symbiyosys"

coverage:
  status:
    project:
      default:
        threshold: 0.5%
        only_pulls: true
    patch:
      default:
        only_pulls: true

comment:
  layout: "diff, reach"
  behavior: new
  require_changes: false
