#!/bin/bash

set -e

WORKDIR=verilator

if [[ -e $WORKDIR/checksum ]] && md5sum --status --check $WORKDIR/checksum; then
  echo "$WORKDIR up to date"
  exit 0
else
  echo "Rebuilding $WORKDIR"
  rm -rf $WORKDIR
fi

mkdir $WORKDIR
pushd $WORKDIR

mkdir install
PREFIX=$(readlink -f install)

# Build verilator
git clone http://github.com/verilator/verilator src
pushd src
git checkout v4.034
unset VERILATOR_ROOT
autoconf
./configure --prefix=$PREFIX CXX=clang++
make -j$(nproc)
make install
popd
rm -rf src

popd

# Update checksum
md5sum $BASH_SOURCE > $WORKDIR/checksum
