################################################################################
# Copyright (c) 2017-2021 Argon Design Ltd. All rights reserved.
# This file is covered by the BSD (with attribution) license.
# See the LICENSE file for the precise wording of the license.
################################################################################

name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  JAVA_OPTS: -Dsbt.ci=true # SBT CI mode (less noise on output)
  CCACHE_MAXSIZE: 64M # ccache used by Verilator during tests, keep small

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-20.04]
        suite: [UnitTests, EndToEndTests, EndToEndParallelTests]
        scala: [2.13.4, 3.0.0-RC1]
    name: ${{ matrix.suite }} Scala ${{ matrix.scala }} Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install APT dependencies
        if: matrix.suite != 'UnitTests'
        run: |
          # ccache - Used by Verilator when running tests
          sudo apt-get install ccache
          # SymbiYosys dependencies
          sudo apt-get install tcl-dev
          sudo apt-get install graphviz
          sudo apt-get install xdot
          sudo apt-get install libftdi-dev
          sudo apt-get install gperf
          sudo apt-get install libboost-program-options-dev
          # Verilator dependencies
          sudo apt-get install libfl-dev
          sudo apt-get install libgoogle-perftools-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache testing tools
        if: matrix.suite != 'UnitTests'
        uses: actions/cache@v2
        with:
          path: |
            symbiyosys
            verilator
          key: ${{ matrix.os }}-testing-tools-${{ hashFiles('setup-*') }}
      - name: Build testing tools
        if: matrix.suite != 'UnitTests'
        run: |
          bash -x ./setup-symbiyosys
          bash -x ./setup-verilator
          ccache -s -z -C
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier
            ~/.ivy2/cache
          key: build-${{ matrix.os }}-SBT-${{ matrix.java }}-${{ matrix.scala }}-${{ matrix.suite }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: build-${{ matrix.os }}-SBT-${{ matrix.java }}-${{ matrix.scala }}-${{ matrix.suite }}-
      - name: Cache ccache
        if: matrix.suite != 'UnitTests'
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: build-${{ matrix.os }}-ccache-${{ github.sha }}
          restore-keys: build-${{ matrix.os }}-ccache-
      - name: Compile
        run: sbt ++${{ matrix.scala }} clean compile Test/compile
      - name: Run tests
        run: sbt ++${{ matrix.scala }} run${{ matrix.suite }}
  format:
    name: Check code formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier
            ~/.ivy2/cache
          key: format-SBT-${{ hashFiles('**/build.sbt') }}
          restore-keys: format-SBT-
      - name: Check code formatting
        run: sbt scalafmtCheckAll scalafmtSbtCheck
  deploy:
    name: Deploy Cloud Function for playground
    needs: build
    if: ${{ github.repository == 'ArgonDesign/alogic' && github.event_name == 'push' && github.ref == 'refs/heads/4.0.x' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need full history for 'git describe', used for version numbers
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier
            ~/.ivy2/cache
          key: deploy-SBT-${{ hashFiles('**/build.sbt') }}
          restore-keys: deploy-SBT-
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy
        run: sbt gcfDeploy
